---
# os tuning

- name: sysctl vm.overcommit_memory=1
  sysctl: 
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.conf

- name: sysctl -w net.core.somaxconn=65535
  sysctl:
    name: net.core.somaxconn
    value: '65535'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.conf

- name: disable transparent hugepages - copy service file
  copy:
    src: disable-transparent-hugepages
    dest: /etc/init.d/disable-transparent-hugepages
    owner: root
    group: root
    mode: 0755

- name: enable service disable-transparent-hugepages
  service:
    name: disable-transparent-hugepages
    enabled: true
    state: started
